name: Run CI tests for Pull Requests or main branch
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  tests:
    name: "Test build"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: "Set up xCherry environment"
        run: wget https://raw.githubusercontent.com/xcherryio/xcherry/main/docker-compose/docker-compose-postgres14-example.yaml && docker compose -f docker-compose-postgres14-example.yaml up -d
      - name: "Run test"
        run: make tests
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - name: Dump docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2